apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-binding
  namespace: hello-dev
spec:
  params:
    - name: git-repo-application
      value: $(body.repository.clone_url)
    - name: git-repo-gitops
      value: "https://github.com/marcelobruckner/hello-gitops-k8s"
    - name: image
      value: "marcelobruckner/hello"
